ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS struggles JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS food_context TEXT,
  ADD COLUMN IF NOT EXISTS cuisines JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS motivations JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS accountability TEXT;
